#!/bin/sh

NFS_CONF="nfs.sh"
MAIN_CONF="configure"
INIT_CONF="init_config"
START_CONF="start_service"
LUA_CONF="scalar/config.lua"

if [ ! -n "$1" ] ;then
	echo "please input a node number!"
	exit 0
fi

if [ ! -n "$2" ] ;then
	echo "please input dest ip!"
	exit 0
fi

# generate nfs.sh file
echo "Generating nfs.sh file..."
echo "#!/bin/sh" > ${NFS_CONF}
echo "mount -t nfs 192.168.$1.10:/home/root/Project /mnt/nfs -o nolock,proto=tcp,nfsvers=3" >> ${NFS_CONF}

# generate configure file
echo "Generating configure file..."
echo "NODE_NUMBER=$1" > ${MAIN_CONF}
echo "IP=192.168.$1.2" >> ${MAIN_CONF}
echo "SER_IP=$2" >> ${MAIN_CONF}
echo "VIDEO_EXIST=0" >> ${MAIN_CONF}
echo "FLAG_GPS=1" >> ${MAIN_CONF}
echo "FLAG_IP=0" >> ${MAIN_CONF}
echo "FLAG_SER=0" >> ${MAIN_CONF}
echo "FLAG_VIDEO=0" >> ${MAIN_CONF}
echo "SLEEP_SEC=5" >> ${MAIN_CONF}

# generate init_config file
echo "Generating init_config file..."
echo "#!/bin/sh" > ${INIT_CONF}
echo "ifconfig eth0 192.168.$1.2 netmask 255.255.255.0" >> ${INIT_CONF}
echo "route add default gw 192.168.$1.1" >> ${INIT_CONF}

# generate start_service file
cur_path=`pwd`
echo "Generating start_service file..."
echo "#!/bin/sh" > ${START_CONF}
echo "cd ${cur_path}" >> ${START_CONF}
echo "./init_config" >> ${START_CONF}
echo "./main_control_arm >> /dev/null &" >> ${START_CONF}
echo "./version_20150427 -i $2 -t 128 -k 500 -c $1 -d 0 -g 20 >> /dev/null &" >> ${START_CONF}
echo "cd ${cur_path}/scalar" >> ${START_CONF}
echo "./lua -g $1 -o 1 main.lua 1>/dev/null 2>&1 &" >> ${START_CONF}

# generate scalar/config.lua file
echo 'Generating scalar/config.lua file...'
echo 'SL_port =' > ${LUA_CONF}
echo '{' >> ${LUA_CONF}
echo '	PATH = "/dev/ttySAC3",  --串口路径,(Top6410: /dev/ttySAC3)' >> ${LUA_CONF}
echo '	BAUD = 9600,           --波特率' >> ${LUA_CONF}
echo '	DATA = 8,               --数据位数' >> ${LUA_CONF}
echo '	PARI = 0,               --奇偶校验' >> ${LUA_CONF}
echo '	STOP = 1                --停止位数' >> ${LUA_CONF}
echo '}' >> ${LUA_CONF}
echo '' >> ${LUA_CONF}
echo '-------------------------------------------------------------' >> ${LUA_CONF}
echo "BY_ADDR = \"$2\"" >> ${LUA_CONF}
echo 'BY_PORT = "7777"' >> ${LUA_CONF}
echo 'XD_ADDR = nil' >> ${LUA_CONF}
echo 'XD_PORT = "7770"' >> ${LUA_CONF}
echo '-------------------------------------------------------------' >> ${LUA_CONF}
echo '' >> ${LUA_CONF}
echo 'INTERVAL = 5' >> ${LUA_CONF}
echo '' >> ${LUA_CONF}
