#!/bin/sh
cd /main_6410
./init_config
./main_control_arm >> /dev/null &
./version_20150414 -i 192.168.4.155 -t 128 -k 500 -c 4 -d 0 -g 20 >> /dev/null &
cd /main_6410/bx
./lua -g 4 -o 1 main.lua 1>/dev/null 2>&1 &
