
RAPTOR_INC_DIR		= $(RAPTOR_BASE)
RAPTOR_SRC_DIR		= $(RAPTOR_BASE)
RAPTOR_OBJ_DIR		= $(RAPTOR_BASE)

RAPTOR_DIRS		= $(RAPTOR_INC_DIR)  $(RAPTOR_SRC_DIR)  $(RAPTOR_OBJ_DIR)
RAPTOR_SRC		= $(wildcard $(RAPTOR_SRC_DIR)/*.c)

RAPTOR_OBJ		= $(RAPTOR_SRC:.c=.o)
RAPTOR_OBJ		:= $(filter %.o, $(RAPTOR_OBJ))
RAPTOR_OBJ		:= $(patsubst $(RAPTOR_SRC_DIR)/%, $(RAPTOR_OBJ_DIR)/%, $(RAPTOR_OBJ)) 

RAPTOR_INC		= -I$(RAPTOR_INC_DIR)
RAPTOR_DEP		= $(wildcard $(RAPTOR_INC_DIR)/*.h)

RAPTOR_CFLAGS	= $(CFLAGS) -lm -std=gnu99


