#!/bin/sh

NFS_CONF="nfs.sh"
POWER_CONF="configure"
ROUTE_CONF="IpNet_config"
START_CONF="start_service"


if [ ! -n "$1" ] ;then
	echo "please input a node number!"
	exit 0
fi

if [ ! -n "$2" ] ;then
	echo "please input dest ip!"
	exit 0
fi

# generate nfs.sh file
echo "Generating nfs.sh file..."
echo "#!/bin/sh" > ${NFS_CONF}
echo "mount -t nfs 192.168.$1.10:/home/root/Project /mnt/nfs -o nolock,proto=tcp,nfsvers=3" >> ${NFS_CONF}


# generate configure file
echo "Generating configure file..."
echo "NODE_ID=$1" > ${POWER_CONF}
echo "OPEN_PORT=/dev/ttyS4" >> ${POWER_CONF}
echo "SETTING_VALUE=1111" >> ${POWER_CONF}
echo "NUMBER=-1" >> ${POWER_CONF}
echo "SLEEP_MINUTE=1" >> ${POWER_CONF}
echo "SEND_IP=$2" >> ${POWER_CONF}
echo "SERVER_PORT=9000" >> ${POWER_CONF}


# generate IpNet_config file
echo "Generating IpNet_config file..."
echo "BroadCastAddr=10.0.3.255" > ${ROUTE_CONF}
echo "BroadPortAddr=10.0.3.$1" >> ${ROUTE_CONF}
echo "BroadCastPort=6666" >> ${ROUTE_CONF}
echo "BroadCastPortName=eth1" >> ${ROUTE_CONF}
echo "BroadCastTime=3" >> ${ROUTE_CONF}
echo "SinkNum=$1" >> ${ROUTE_CONF}
echo "SinkCount=9" >> ${ROUTE_CONF}
echo "HostIp=10.0.1.$1 10.0.3.$1" >> ${ROUTE_CONF}
echo "SendIp=202.202.96.33 10.0.3.100" >> ${ROUTE_CONF}
echo "NetMask=255.255.255.0 255.255.255.0" >> ${ROUTE_CONF}
echo "NetGw=10.0.1.100 0.0.0.0" >> ${ROUTE_CONF}
echo "DestIp=$2" >> ${ROUTE_CONF}
echo "HAS_SATELLITE=NO" >> ${ROUTE_CONF}
echo "INFO_SERVER_PATH=/var/info_server_path" >> ${ROUTE_CONF}
echo "AGENT_SERVER_IP=222.128.13.159" >> ${ROUTE_CONF}
echo "AGENT_SERVER_PORT=9999" >> ${ROUTE_CONF}

# generate start_service file
echo "Generating start_service file..."
echo "#!/bin/sh" > ${START_CONF}
echo "./arm_energy_v3 >> /dev/null &" >> ${START_CONF}
echo "./arm_Route >> /dev/null &" >> ${START_CONF}
echo "./camctrl -i $2 -c $1 >> /dev/null &" >> ${START_CONF}

